// FPGADebugEngine.idl : IDL source for FPGADebugEngine
//

// This file will be processed by the MIDL tool to
// produce the type library (FPGADebugEngine.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "msdbg.idl";

[
	uuid(84f4a577-a2f8-49f0-aa2c-9526af8df3ee),
	version(1.0),
]
library FPGADebugEngineLib
{
	importlib("stdole2.tlb");
	[
		uuid(E13B43AC-F1B2-4636-A20A-364ACB053A04)
	]
	coclass Engine
	{
		[default] interface IDebugEngine2;
	};
	[
		uuid(1a8f209c-1993-40ef-8a32-26c0fbd415b0)
	]
	coclass FPGADebugProcess
	{
		[default] interface IDebugProcess2;
	};
	[
		uuid(ca8b28d5-faaa-47e8-a8eb-0049fe3d0b18)
	]
	coclass FPGADebugProgram
	{
		[default] interface IDebugProgram2;
	};
	[
		uuid(6ee3fdcc-226f-4daf-ba00-cfacb76d7393)
	]
	coclass FPGADebugProgramEnumerator
	{
		[default] interface IEnumDebugPrograms2;
	};
	[
		uuid(cf63b309-ce44-48d0-adff-4d1fb50f6e26)
	]
	coclass FPGADebugProcessCreateEvent2
	{
		[default] interface IDebugProcessCreateEvent2;
	};
	[
		uuid(099af354-8930-49eb-a95d-72792d509658)
	]
	coclass FPGADebugThread2
	{
		[default] interface IDebugThread2;
	};
	[
		uuid(1f4f6d7b-e4f0-40b8-b3fc-8a6eb00e92b3)
	]
	coclass FPGADebugProgramCreateEvent2
	{
		[default] interface IDebugProgramCreateEvent2;
	};
	[
		uuid(2572f753-9309-4246-8c65-58bd4d427ce2)
	]
	coclass FPGADebugPortSupplier2
	{
		[default] interface IDebugPortSupplier2;
	};
	[
		uuid(fe85e1f0-a6cd-4e87-9ab1-db4ad77b94cd)
	]
	coclass FPGADebugProgramProvider2
	{
		[default] interface IDebugProgramProvider2;
	};
	[
		uuid(968191bd-5c47-4474-bff6-d613b2c353bd)
	]
	coclass FPGADebugPort2
	{
		[default] interface IDebugPort2;
	};
};

import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
